# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: mxl_db

production:
  <<: *default
  database: mxl_db

test:
  <<: *default
  database: mxl_db